### ISSUE TITLE
Broken home page

### ISSUE THREAD

**Issue by yagyamalik** [abhiti01/gator-study#1]
Dashboard on introduction page is not functional, css and designing needed to add pomodoro timer. Also need to fix the menu bar on the left
<img width="1103" alt="Screenshot 2022-01-20 at 4 29 41 PM" src="https://user-images.githubusercontent.com/56045905/150425095-b098d554-18d1-4203-b844-edc6fadd2401.png">

**Comment by abhiti01** [comment]
Replaced broken notification alert button with Log In avatar in branch v1.1 (don't merge yet)

**Comment by abhiti01** [comment]
added list-items.js for drawer items in left menu bar. Linked login and signup page to home page.
